steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/thebestofthebest-411009/train', '.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/thebestofthebest-411009/train']